// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sun, 16 Jan 2022 00:51:38 CET.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include <stdlib.h>
#include "include/Processing.NDI.Lib.h"
#pragma once

#define __CGOGEN 1

